//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adam.Trading.Mechanical.View.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Adam.Trading.Mechanical.View.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string AppError {
            get {
                return ResourceManager.GetString("AppError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Unexpected Error has Occurred. You may continue working or shutdown..
        /// </summary>
        public static string AppUnhandledExceptionMessage {
            get {
                return ResourceManager.GetString("AppUnhandledExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string ChartControlMaxDate {
            get {
                return ResourceManager.GetString("ChartControlMaxDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string ChartControlMinDate {
            get {
                return ResourceManager.GetString("ChartControlMinDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benchmark Return.
        /// </summary>
        public static string Gann2DayBenchmarkReturn {
            get {
                return ResourceManager.GetString("Gann2DayBenchmarkReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        public static string Gann2DayCalculate {
            get {
                return ResourceManager.GetString("Gann2DayCalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gann Swing.
        /// </summary>
        public static string Gann2DaySwingSystem {
            get {
                return ResourceManager.GetString("Gann2DaySwingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Two Day Swing system based on W.D. Gann&apos;s Commodities Course.
        /// </summary>
        public static string Gann2DaySwingSystem_Show_Tooltip {
            get {
                return ResourceManager.GetString("Gann2DaySwingSystem_Show_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gann 2 Day Swing Charts.
        /// </summary>
        public static string Gann2DaySwingWindow_Title {
            get {
                return ResourceManager.GetString("Gann2DaySwingWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to open file browser.
        /// </summary>
        public static string Gann2DayWindow_File_ToolTip {
            get {
                return ResourceManager.GetString("Gann2DayWindow_File_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dollars/Point.
        /// </summary>
        public static string GannDollarsPerPoint {
            get {
                return ResourceManager.GetString("GannDollarsPerPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Stop Hi/Lo.
        /// </summary>
        public static string GannEntryStopExceedHiLo {
            get {
                return ResourceManager.GetString("GannEntryStopExceedHiLo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Stop Retracement.
        /// </summary>
        public static string GannEntryStopRetracement {
            get {
                return ResourceManager.GetString("GannEntryStopRetracement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Stop.
        /// </summary>
        public static string GannExitStop {
            get {
                return ResourceManager.GetString("GannExitStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input File.
        /// </summary>
        public static string GannInputFile {
            get {
                return ResourceManager.GetString("GannInputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Contracts Calc..
        /// </summary>
        public static string GannNoContractsCalc {
            get {
                return ResourceManager.GetString("GannNoContractsCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent Risk.
        /// </summary>
        public static string GannPercentRisk {
            get {
                return ResourceManager.GetString("GannPercentRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skid Points.
        /// </summary>
        public static string GannSkidPoints {
            get {
                return ResourceManager.GetString("GannSkidPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Equity.
        /// </summary>
        public static string GannStartingEquity {
            get {
                return ResourceManager.GetString("GannStartingEquity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use ATR.
        /// </summary>
        public static string GannUseATR {
            get {
                return ResourceManager.GetString("GannUseATR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Current Equity.
        /// </summary>
        public static string GannUseCurrentEquity {
            get {
                return ResourceManager.GetString("GannUseCurrentEquity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benchmark Return.
        /// </summary>
        public static string KrauseBenchmarkReturn {
            get {
                return ResourceManager.GetString("KrauseBenchmarkReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        public static string KrauseCalculate {
            get {
                return ResourceManager.GetString("KrauseCalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dollars/Point.
        /// </summary>
        public static string KrauseDollarsPerPoint {
            get {
                return ResourceManager.GetString("KrauseDollarsPerPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Stop Hi/Lo.
        /// </summary>
        public static string KrauseEntryStopExceedHiLo {
            get {
                return ResourceManager.GetString("KrauseEntryStopExceedHiLo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Stop Retracement.
        /// </summary>
        public static string KrauseEntryStopRetracement {
            get {
                return ResourceManager.GetString("KrauseEntryStopRetracement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix.
        /// </summary>
        public static string KrauseFixContracts {
            get {
                return ResourceManager.GetString("KrauseFixContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input File.
        /// </summary>
        public static string KrauseInputFile {
            get {
                return ResourceManager.GetString("KrauseInputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Contracts/$10000.
        /// </summary>
        public static string KrauseNoContracts {
            get {
                return ResourceManager.GetString("KrauseNoContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retracement Stop.
        /// </summary>
        public static string KrauseRetracementStop {
            get {
                return ResourceManager.GetString("KrauseRetracementStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skid Points.
        /// </summary>
        public static string KrauseSkidPoints {
            get {
                return ResourceManager.GetString("KrauseSkidPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Equity.
        /// </summary>
        public static string KrauseStartingEquity {
            get {
                return ResourceManager.GetString("KrauseStartingEquity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krause Basic System.
        /// </summary>
        public static string KrauseSystem {
            get {
                return ResourceManager.GetString("KrauseSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robert Krause&apos;s Basic Two Day Swing System from his book.
        /// </summary>
        public static string KrauseSystem_Show_Tooltip {
            get {
                return ResourceManager.GetString("KrauseSystem_Show_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use ATR.
        /// </summary>
        public static string KrauseUseATR {
            get {
                return ResourceManager.GetString("KrauseUseATR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        public static string KrauseUseRetracementStop {
            get {
                return ResourceManager.GetString("KrauseUseRetracementStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to open file browser.
        /// </summary>
        public static string KrauseWindow_File_ToolTip {
            get {
                return ResourceManager.GetString("KrauseWindow_File_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krause Basic System.
        /// </summary>
        public static string KrauseWindow_Title {
            get {
                return ResourceManager.GetString("KrauseWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adam&apos;s Mechanical Trading Systems Application.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benchmark Return.
        /// </summary>
        public static string SupportResistanceBenchmarkReturn {
            get {
                return ResourceManager.GetString("SupportResistanceBenchmarkReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        public static string SupportResistanceCalculate {
            get {
                return ResourceManager.GetString("SupportResistanceCalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input File.
        /// </summary>
        public static string SupportResistanceInputFile {
            get {
                return ResourceManager.GetString("SupportResistanceInputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Term Support and Resistance Days.
        /// </summary>
        public static string SupportResistanceLongTerm {
            get {
                return ResourceManager.GetString("SupportResistanceLongTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent Risk.
        /// </summary>
        public static string SupportResistancePercentRisk {
            get {
                return ResourceManager.GetString("SupportResistancePercentRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Term Support and Resistance Days.
        /// </summary>
        public static string SupportResistanceShortTerm {
            get {
                return ResourceManager.GetString("SupportResistanceShortTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skid Fraction.
        /// </summary>
        public static string SupportResistanceSkidFraction {
            get {
                return ResourceManager.GetString("SupportResistanceSkidFraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Equity.
        /// </summary>
        public static string SupportResistanceStartingEquity {
            get {
                return ResourceManager.GetString("SupportResistanceStartingEquity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sekykota Support Resistance.
        /// </summary>
        public static string SupportResistanceSystem {
            get {
                return ResourceManager.GetString("SupportResistanceSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ed Sekykota&apos;s Support and Resistance System from his Web Site.
        /// </summary>
        public static string SupportResistanceSystem_Show_Tooltip {
            get {
                return ResourceManager.GetString("SupportResistanceSystem_Show_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to open file browser.
        /// </summary>
        public static string SupportResistanceWindow_File_ToolTip {
            get {
                return ResourceManager.GetString("SupportResistanceWindow_File_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sekyota Support and Resistance.
        /// </summary>
        public static string SupportResistanceWindow_Title {
            get {
                return ResourceManager.GetString("SupportResistanceWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tick Size.
        /// </summary>
        public static string TickSize {
            get {
                return ResourceManager.GetString("TickSize", resourceCulture);
            }
        }
    }
}
