//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adam.Trading.Mechanical.ViewModel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Adam.Trading.Mechanical.ViewModel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Benchmark Return is not numeric.
        /// </summary>
        internal static string BenchMarkReturnNotNumeric {
            get {
                return ResourceManager.GetString("BenchMarkReturnNotNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Dollars/Point must be greater than zero.
        /// </summary>
        internal static string DollarsPerPointLessZero {
            get {
                return ResourceManager.GetString("DollarsPerPointLessZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Dollars/Point is not numeric.
        /// </summary>
        internal static string DollarsPerPointNotNumeric {
            get {
                return ResourceManager.GetString("DollarsPerPointNotNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Entry Stop for Exceed Hi Lo is less than zero.
        /// </summary>
        internal static string EntryStopExceedHiLoLessZero {
            get {
                return ResourceManager.GetString("EntryStopExceedHiLoLessZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Entry Stop for Exceed Hi Lo is not numeric.
        /// </summary>
        internal static string EntryStopExceedHiLoNotNumeric {
            get {
                return ResourceManager.GetString("EntryStopExceedHiLoNotNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Entry Stop for Retracement is less than zero.
        /// </summary>
        internal static string EntryStopRetracementLessZero {
            get {
                return ResourceManager.GetString("EntryStopRetracementLessZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Entry Stop for Retracement is not numeric.
        /// </summary>
        internal static string EntryStopRetracementNotNumeric {
            get {
                return ResourceManager.GetString("EntryStopRetracementNotNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Exit Stop is less than zero.
        /// </summary>
        internal static string ExitStopLessZero {
            get {
                return ResourceManager.GetString("ExitStopLessZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Exit Stop is not numeric.
        /// </summary>
        internal static string ExitStopNotNumeric {
            get {
                return ResourceManager.GetString("ExitStopNotNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Input File is missing.
        /// </summary>
        internal static string InputFileMissing {
            get {
                return ResourceManager.GetString("InputFileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Term Support/Resistance Days must be greater than Short Term.
        /// </summary>
        internal static string LongTermLessShortTerm {
            get {
                return ResourceManager.GetString("LongTermLessShortTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Term support/Resistance Days must be greater than zero.
        /// </summary>
        internal static string LongTermLessZero {
            get {
                return ResourceManager.GetString("LongTermLessZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Term Support/Resistance Days must be an integer.
        /// </summary>
        internal static string LongTermNotNumeric {
            get {
                return ResourceManager.GetString("LongTermNotNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Benchmark Return is missing.
        /// </summary>
        internal static string NoBenchMarkReturnEntered {
            get {
                return ResourceManager.GetString("NoBenchMarkReturnEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The No. of Contracts is missing.
        /// </summary>
        internal static string NoContractsEntered {
            get {
                return ResourceManager.GetString("NoContractsEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The No. of Contracts must be greater than zero.
        /// </summary>
        internal static string NoContractsLessZero {
            get {
                return ResourceManager.GetString("NoContractsLessZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The No. of Contracts is not numeric.
        /// </summary>
        internal static string NoContractsNotNumeric {
            get {
                return ResourceManager.GetString("NoContractsNotNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Dollars/Point is missing.
        /// </summary>
        internal static string NoDollarsPerPointEntered {
            get {
                return ResourceManager.GetString("NoDollarsPerPointEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Entry Stop for Pyramid entered.
        /// </summary>
        internal static string NoEntryStopPyramidEntered {
            get {
                return ResourceManager.GetString("NoEntryStopPyramidEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Entry Stop for Retracement entered.
        /// </summary>
        internal static string NoEntryStopRetracementEntered {
            get {
                return ResourceManager.GetString("NoEntryStopRetracementEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Exit Stop entered.
        /// </summary>
        internal static string NoExitStopEntered {
            get {
                return ResourceManager.GetString("NoExitStopEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Term Support/Resistance Days is missing.
        /// </summary>
        internal static string NoLongTermEntered {
            get {
                return ResourceManager.GetString("NoLongTermEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Percent Risk is missing.
        /// </summary>
        internal static string NoPercentRiskEntered {
            get {
                return ResourceManager.GetString("NoPercentRiskEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Retracement Fraction is missing.
        /// </summary>
        internal static string NoRetracementFractionEntered {
            get {
                return ResourceManager.GetString("NoRetracementFractionEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Term Support/Resistance Days is missing.
        /// </summary>
        internal static string NoShortTermEntered {
            get {
                return ResourceManager.GetString("NoShortTermEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Skid Fraction is missing.
        /// </summary>
        internal static string NoSkidFractionEntered {
            get {
                return ResourceManager.GetString("NoSkidFractionEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Skid Points is missing.
        /// </summary>
        internal static string NoSkidPointsEntered {
            get {
                return ResourceManager.GetString("NoSkidPointsEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Starting Equity is missing.
        /// </summary>
        internal static string NoStartingEquityEntered {
            get {
                return ResourceManager.GetString("NoStartingEquityEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Ticks for Entry is missing.
        /// </summary>
        internal static string NoTicksForEntryEntered {
            get {
                return ResourceManager.GetString("NoTicksForEntryEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Tick Size is missing.
        /// </summary>
        internal static string NoTickSizeEntered {
            get {
                return ResourceManager.GetString("NoTickSizeEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Percent Risk must be greater than zero.
        /// </summary>
        internal static string PercentRiskLessZero {
            get {
                return ResourceManager.GetString("PercentRiskLessZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Percent Risk is not numeric.
        /// </summary>
        internal static string PercentRiskNotNumeric {
            get {
                return ResourceManager.GetString("PercentRiskNotNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Retracement Fraction is less than zero.
        /// </summary>
        internal static string RetracementFractionLessZero {
            get {
                return ResourceManager.GetString("RetracementFractionLessZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Retracement Fraction is not numeric.
        /// </summary>
        internal static string RetracementFractionNotNumeric {
            get {
                return ResourceManager.GetString("RetracementFractionNotNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Term support/Resistance Days must be greater than zero.
        /// </summary>
        internal static string ShortTermLessZero {
            get {
                return ResourceManager.GetString("ShortTermLessZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Term Support/Resistance Days must be an integer.
        /// </summary>
        internal static string ShortTermNotNumeric {
            get {
                return ResourceManager.GetString("ShortTermNotNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Skid Fraction must be greater than zero.
        /// </summary>
        internal static string SkidFractionLessZero {
            get {
                return ResourceManager.GetString("SkidFractionLessZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Skid Fraction is not numeric.
        /// </summary>
        internal static string SkidFractionNotNumeric {
            get {
                return ResourceManager.GetString("SkidFractionNotNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Skid Points is less than zero.
        /// </summary>
        internal static string SkidPointsLessZero {
            get {
                return ResourceManager.GetString("SkidPointsLessZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Skid Points is not numeric.
        /// </summary>
        internal static string SkidPointsNotNumeric {
            get {
                return ResourceManager.GetString("SkidPointsNotNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Starting Equity must be greater than zero.
        /// </summary>
        internal static string StartingEquityLessZero {
            get {
                return ResourceManager.GetString("StartingEquityLessZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Starting Equity is not numeric.
        /// </summary>
        internal static string StartingEquityNotNumeric {
            get {
                return ResourceManager.GetString("StartingEquityNotNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Ticks for entry is less than zero.
        /// </summary>
        internal static string TicksForEntryLessZero {
            get {
                return ResourceManager.GetString("TicksForEntryLessZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Ticks for Entry is not numeric.
        /// </summary>
        internal static string TicksForEntryNotNumeric {
            get {
                return ResourceManager.GetString("TicksForEntryNotNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Tick Size must be greater than zero.
        /// </summary>
        internal static string TickSizeLessZero {
            get {
                return ResourceManager.GetString("TickSizeLessZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Tick Size is not numeric.
        /// </summary>
        internal static string TickSizeNotNumeric {
            get {
                return ResourceManager.GetString("TickSizeNotNumeric", resourceCulture);
            }
        }
    }
}
